### ISSUE TITLE
Executing detekt with pipeline in bitbucket 

### ISSUE THREAD

**Issue by rreynoud** [arturbosch/detekt#1090]
Im trying to execute detekt with bitbucket. It works on my local machine but not on bitbucket pipeline.
I have the following bitbucket-pipelines.yml:
```yml
image: gradle

pipelines:
  default:
  - step:
      caches:
      - gradle
      script:
        - gradle clean --stacktrace
        - gradle compilekotlin
        - gradle compilejava
        - gradle test
        - gradle build
        - gradle detektcheck

```
and the following build.gradle:

```yml
buildscript {
    ext {
        jwt_version = '0.9.0'
        kotlin_version = '1.2.60'
        spek_version = '1.1.5'
        jupiter_version = '5.2.0'
        junit_version = '1.0.0'
        mockito_version = '2.19.0'
        coroutines_version = '0.23.4'
        spring_version = '2.0.3.RELEASE'

        spring_boot_group = 'org.springframework.boot'
        spring_security_group = 'org.springframework.security'
        spring_rest_docs_group = 'org.springframework.restdocs'
        kotlin_group = 'org.jetbrains.kotlin'
        kotlinx_group = 'org.jetbrains.kotlinx'
        spek_group = 'org.jetbrains.spek'
        junit_group = 'org.junit.platform'
        jupiter_group = 'org.junit.jupiter'
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
        mavenLocal()
    }
    dependencies {
        classpath "$kotlin_group:kotlin-gradle-plugin:$kotlin_version"
        classpath "$spring_boot_group:spring-boot-gradle-plugin:$spring_version"
        classpath "$junit_group:junit-platform-gradle-plugin:$junit_version"
        classpath "org.asciidoctor:asciidoctor-gradle-plugin:1.5.3"
        classpath "org.jetbrains.kotlin:kotlin-allopen:$kotlin_version"
    }
}

plugins {
    id "io.gitlab.arturbosch.detekt" version "1.0.0.RC8"
}

detekt {
    version = "1.0.0.RC8"
    profile("main") {
        config = "$project.rootDir/detekt-config.yml"
        filters = ".*test.*,.*/resources/.*,.*/tmp/.*"
        output = "${project.buildDir}/reports/detekt.xml"
        parallel = true
        disableDefaultRuleSets = false
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://maven.google.com" }
        maven { url "http://dl.bintray.com/jetbrains/spek" }
        maven { url 'https://repo.spring.io/libs-release' }
        maven {
            name "teorema-commons-site"
            url "http://webservice.teorema.inf.br:5050/repository/local.teorema.commons.repo/"
            credentials {
                username = 'admin'
                password = 'admin1'
            }
        }
        mavenCentral()
        mavenLocal()
    }
}

apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'kotlin'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'org.junit.platform.gradle.plugin'
apply plugin: 'org.asciidoctor.convert'

group 'br.inf.teorema'
version '1.0-SNAPSHOT'


war {
    archiveName = 'api-java.war'
}

sourceCompatibility = 1.8
targetCompatibility = 1.8
compileKotlin {
    kotlinOptions {
        freeCompilerArgs = ["-Xjsr305=strict"]
        jvmTarget = "1.8"
    }
}
compileTestKotlin {
    kotlinOptions {
        freeCompilerArgs = ["-Xjsr305=strict"]
        jvmTarget = "1.8"
    }
}

repositories {
    mavenCentral()
    maven {
        url "http://repository.jetbrains.com/all"
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
        resources {
            srcDir { 'src/main/resources' }
        }

    }
}


junitPlatform {
    filters {
        engines {
            include 'spek'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "$kotlin_group:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "$kotlin_group:kotlin-reflect:$kotlin_version"
    implementation "$kotlinx_group:kotlinx-coroutines-core:$coroutines_version"
    implementation("$spring_boot_group:spring-boot-starter-web") {
        exclude module: "spring-boot-starter-tomcat"
    }
    implementation "$spring_boot_group:spring-boot-starter-validation"
    implementation "$spring_boot_group:spring-boot-devtools"
    implementation "io.jsonwebtoken:jjwt:$jwt_version"
    implementation 'br.com.samuelweb:java-nfe:4.00.7a'
    implementation 'javax.servlet.jsp.jstl:javax.servlet.jsp.jstl-api:1.2.1'
    implementation 'javax.servlet:javax.servlet-api:4.0.1'
    implementation 'com.fasterxml.jackson.module:jackson-module-kotlin'
}

dependencies {
    testImplementation "$spring_boot_group:spring-boot-starter-test"
    testImplementation "$spring_security_group:spring-security-test"
    testImplementation "$spring_rest_docs_group:spring-restdocs-mockmvc"
    testImplementation "org.mockito:mockito-core:$mockito_version"
    testImplementation "$spek_group:spek-api:$spek_version"
    testImplementation "$spek_group:spek-junit-platform-engine:$spek_version"
    testImplementation "$kotlin_group:kotlin-reflect:$kotlin_version"
    testImplementation "$kotlin_group:kotlin-test:$kotlin_version"
    testImplementation "$junit_group:junit-platform-runner:$junit_version"
    testImplementation "$junit_group:junit-platform-launcher:$junit_version"
    testImplementation "$jupiter_group:junit-jupiter-engine:$jupiter_version"
    testImplementation "$jupiter_group:junit-jupiter-api:$jupiter_version"
}

```

We noticed that without the following piece of code it works on bitbucket:

```yml
plugins {
    id "io.gitlab.arturbosch.detekt" version "1.0.0.RC8"
}

detekt {
    version = "1.0.0.RC8"
    profile("main") {
        config = "$project.rootDir/detekt-config.yml"
        filters = ".*test.*,.*/resources/.*,.*/tmp/.*"
        output = "${project.buildDir}/reports/detekt.xml"
        parallel = true
        disableDefaultRuleSets = false
    }
}
```

```java
FAILURE: Build failed with an exception.
* Where:
Build file '/opt/atlassian/pipelines/agent/build/build.gradle' line: 37
* What went wrong:
Plugin [id: 'io.gitlab.arturbosch.detekt', version: '1.0.0.RC8'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:1.0.0.RC8')
  Searched in the following repositories:
    Gradle Central Plugin Repository
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'io.gitlab.arturbosch.detekt', version: '1.0.0.RC8'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:1.0.0.RC8')
  Searched in the following repositories:
    Gradle Central Plugin Repository
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:262)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.access$100(DefaultPluginRequestApplicator.java:63)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1.transform(DefaultPluginRequestApplicator.java:91)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1.transform(DefaultPluginRequestApplicator.java:88)
	at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:204)

```

We already tried to solve it in various manners. The project has java and kotlin files.

## Expected Behavior
Should work on bitbucket too

## Current Behavior
Works locally but not on bitbucket

## Your Environment
* Version used: 1.0.0.RC8
* Operating System and version: Linux Mint 19 Tara

**Comment by arturbosch** [comment]
Thats strange. The plugin is configured the right way as far as I see.
Hm. Try adding this maven repository: `repositories { maven { http://dl.bintray.com/arturbosch/code-analysis/ } }`. Its the original detekt repository.
Maybe you can also try out the old way to configure plugins:
```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0.RC8"
  }
}

apply plugin: "io.gitlab.arturbosch.detekt"
```

**Comment by erchenger** [comment]
I am also seeing the same problem. It looks like sometimes it is being pointed to a URL where the dependency doesn't exist. I know in the past this has been due to Jcenter and their CDNs failing or doing weird things. Not sure if that is the case here but may be worth looking into.

**Comment by erchenger** [comment]
`* What went wrong:
Error resolving plugin [id: 'io.gitlab.arturbosch.detekt', version: '1.0.0.RC8']
> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
   > Could not determine artifacts for io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:1.0.0.RC8
      > Could not get resource 'https://plugins.gradle.org/m2/io/gitlab/arturbosch/detekt/io.gitlab.arturbosch.detekt.gradle.plugin/1.0.0.RC8/io.gitlab.arturbosch.detekt.gradle.plugin-1.0.0.RC8.jar'.
         > Could not HEAD 'https://plugins.gradle.org/m2/io/gitlab/arturbosch/detekt/io.gitlab.arturbosch.detekt.gradle.plugin/1.0.0.RC8/io.gitlab.arturbosch.detekt.gradle.plugin-1.0.0.RC8.jar'.
            > Read timed out`

**Comment by 3flex** [comment]
Which version of Gradle are you using @erchenger @jshvarts @rreynoud ?

**Comment by erchenger** [comment]
@3flex 4.4

**Comment by jshvarts** [comment]
@3flex 4.6

**Comment by arturbosch** [comment]
Any chance to use gradle 4.9 or higher?

**Comment by arturbosch** [comment]
Yes, RC9+ just support gradle 4.9 or higher. I do not know the supported minimum gradle version for RC8 anymore, sorry.
Any chance to also try out RC11? Maybe it is also a coordination switching problem, but would not explain why it works locally byt not on bitbucket ...
