### ISSUE TITLE
IndexOutOfBoundsException when changing --output to --report with RC9

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#1114]
Seems like the Detekt's executable lost the `--output` parameter with RC9. The new one that should be used is `--report`. After changing it I'm getting the following exception though:

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.Collections$SingletonList.get(Collections.java:4815)
        at io.gitlab.arturbosch.detekt.cli.ReportPath$Companion.from(ReportPath.kt:17)
        at io.gitlab.arturbosch.detekt.cli.CliArgs$reportPaths$2.invoke(CliArgs.kt:88)
        at io.gitlab.arturbosch.detekt.cli.CliArgs$reportPaths$2.invoke(CliArgs.kt:14)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.gitlab.arturbosch.detekt.cli.CliArgs.getReportPaths(CliArgs.kt)
        at io.gitlab.arturbosch.detekt.cli.OutputFacade.<init>(OutputFacade.kt:21)
        at io.gitlab.arturbosch.detekt.cli.runners.Runner.execute(Runner.kt:24)
        at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:24)
```

The reason is that I don't comply with the new format `report-id:path-to-store-report`. In any case, I should get a more meaningful exception message than an IndexOutOfBoundsException.

I was passing a directory path and there is no `:` hence the split does not split anything and index 1 ain't there.

**Comment by marschwar** [comment]
The problem is that `assert` will only raise a runtime exception if explicitly enabled.
```Throws an AssertionError if the value is false and runtime assertions have been enabled on the JVM using the -ea JVM option.```

I will change the existing check to something else and create a PR.

**Comment by pavlospt** [comment]
@marschwar can you check if what you are describing is resolved here: https://github.com/arturbosch/detekt/pull/1145 ?

**Comment by marschwar** [comment]
Good point. Since that commit already changed the check from `assert` to `require` it is already taken care of. In my opinion this can be closed then.
