### ISSUE TITLE
Running RC9 gradlew detekt crashes with detekt-formatting included

### ISSUE THREAD

**Issue by jukkasi** [arturbosch/detekt#1143]
## Expected Behavior
Detekt runs fine using Gradle and reports formatter problems

## Current Behavior
Detekt crashes if detekt-formatter is included in Gradle configuration
```
Task :detekt FAILED
Error: Could not find or load main class io.gitlab.arturbosch.detekt.cli.Main

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':detekt'.
> Process 'command 'C:\java\jdk1.8.0_131\bin\java.exe'' finished with non-zero exit value 1
```
## Steps to Reproduce (for bugs)
1. Configure Detekt RC9 for Gradle, detektVersion = 1.0.0.RC9
```
buildscript {
       dependencies {
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:${detektVersion}"
...
```
2. Using settings:
```
detekt {
    toolVersion = "${detektVersion}"
    input = files("src/main/kotlin","src/test/kotlin")
    config = files("detekt.yml")
    filters = ".*/resources/.*,.*/tmp/.*"
}
```
3. Include detekt-formatter RC9
```
dependencies {
    detekt("io.gitlab.arturbosch.detekt:detekt-formatting:${detektVersion}")
...
```
4. Run gradlew detekt -> detekt crashes
5. Remove detekt-formatting dependency in Gradle configuration and gradlew detekt runs fine

## Your Environment

* Version used: Detekt RC9
* Operating System and version: Win10 & Gradle 4.9
* Link to your project:

**Comment by pavlospt** [comment]
Could you possibly run it with `--stacktrace` and `--debug` in two separate runs and post the results here :) ?

**Comment by ychescale9** [comment]
**`./gradlew app:detekt --stacktrace`**

```
> Task :app:detekt FAILED
Error: Could not find or load main class io.gitlab.arturbosch.detekt.cli.Main

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:detekt'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:detekt'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:105)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:79)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:395)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:37)
        at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:225)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1102)
        at io.gitlab.arturbosch.detekt.invoke.DetektInvoker.invokeCli$detekt_gradle_plugin(DetektInvoker.kt:13)
        at io.gitlab.arturbosch.detekt.Detekt.check(Detekt.kt:110)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 33 more
```

**Comment by ychescale9** [comment]
**`./gradlew app:detekt --debug`**: [results](https://gist.github.com/ychescale9/4660f90bc918d1c0e1e1e0b6ebab9034)

**Comment by ychescale9** [comment]
https://github.com/ychescale9/release-probe
Sorry it's not exactly small but you can reproduce it with running `detekt` against any of the modules:)

**Comment by pavlospt** [comment]
Great will check it!

**Comment by 3flex** [comment]
Can you please try:
```kotlin
dependencies {
    detekt("io.gitlab.arturbosch.detekt:detekt-formatting:${detektVersion}")
    detekt("io.gitlab.arturbosch.detekt:detekt-cli:${detektVersion}")
}
```

The Gradle plugin provides a default dependency of `detekt-cli`, but it's being overwritten by the `detekt-formatting` dependency. Adding both explicitly should work for now.

**Comment by Mauin** [comment]
Yep, I'm seeing the same that @3flex is describing. Any `detekt` dependency is overwriting the default dependency to `detekt-cli`. I have a fix lined up.

**Comment by ychescale9** [comment]
Thanks adding `detekt("io.gitlab.arturbosch.detekt:detekt-cli:${detektVersion}")
}` works.

**Comment by arturbosch** [comment]
+1 thanks guys!
