### ISSUE TITLE
java 9 - reflection cannot make constructor private

### ISSUE THREAD

**Issue by binkley** [arturbosch/detekt#12]
A Java 9 issue related to reflection.  I ran `java -jar .../detekt-cli.jar -p .` against a simple Kotlin project, using Java 9 (build 9-ea+159):

```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private jdk.internal.reflect.ConstructorAccessor java.lang.reflect.Constructor.acquireConstructorAccessor() accessible: module java.base does not "opens java.lang.reflect" to unnamed module @34c4973
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
        at com.intellij.util.ReflectionUtil.findMethod(ReflectionUtil.java:265)
        at com.intellij.util.ReflectionUtil.getDeclaredMethod(ReflectionUtil.java:279)
        at com.intellij.util.ReflectionUtil.<clinit>(ReflectionUtil.java:422)
        ... 14 more
```

**Comment by arturbosch** [comment]
Thx for the report. I've never tested detekt on Java 9 but this seems like a problem from within the kotlin-compiler which will likely be fixed for the Java9 release. I will keep track of this!

**Comment by arturbosch** [comment]
On 9ea167 I was able to run detekt. Unfortunatly java.xml.bind was removed from base module so I need to add `--add-modules java.se.ee` or `--add-modules java.xml.bind` on each run ... Need more research on what to do about this.

**Comment by arturbosch** [comment]
Fixed in M10.3.

**Comment by binkley** [comment]
Thanks!
