### ISSUE TITLE
M12.1 fails with "URISyntaxException: Illegal character in authority at index 7" under windows

### ISSUE THREAD

**Issue by ovsyankin** [arturbosch/detekt#128]
I'm running detekt with maven on windows. Here is my config

```xml
<phase>validate</phase>
<configuration>
    <target name="detekt">
        <java taskname="detekt"
              dir="${project.basedir}"
              fork="true"
              failonerror="true"
              classname="io.gitlab.arturbosch.detekt.cli.Main"
              classpathref="maven.plugin.classpath">
            <arg value="--project"/>
            <arg value="${project.basedir}"/>
            <arg value="--config"/>
            <arg value="${project.basedir}/build/src/main/resources/omc-detekt.yml"/>
            <arg value="--filters"/>
            <arg value=".*test.*"/>
            <arg value="--output"/>
            <arg value="${project.build.directory}/detekt-report/detekt.xml"/>
        </java>
    </target>
</configuration>
```

Failure log:
```
[Acceptance tests] [INFO] Executing tasks
[Acceptance tests] 
[Acceptance tests] detekt:
[Acceptance tests]    [detekt] Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in authority at index 7: file://C:\Jenkins\workspace\hes_enhancement_bump_detekt-ZXXJCVCLV6URFQ7ERNCH6PULFPARMMDBNRIPX4SZJF6HGEGM3TTA
[Acceptance tests]    [detekt] 	at java.net.URI.create(URI.java:852)
[Acceptance tests]    [detekt] 	at io.gitlab.arturbosch.detekt.cli.ExistingPathConverter.convert(PathConverters.kt:16)
[Acceptance tests]    [detekt] 	at io.gitlab.arturbosch.detekt.cli.ExistingPathConverter.convert(PathConverters.kt:14)
[Acceptance tests]    [detekt] 	at com.beust.jcommander.JCommander.convertValue(JCommander.java:1472)
[Acceptance tests]    [detekt] 	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:238)
[Acceptance tests]    [detekt] 	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:895)
[Acceptance tests]    [detekt] 	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:870)
[Acceptance tests]    [detekt] 	at com.beust.jcommander.JCommander.parseValues(JCommander.java:721)
[Acceptance tests]    [detekt] 	at com.beust.jcommander.JCommander.parse(JCommander.java:340)
[Acceptance tests]    [detekt] 	at com.beust.jcommander.JCommander.parse(JCommander.java:319)
[Acceptance tests]    [detekt] 	at io.gitlab.arturbosch.detekt.cli.JCommanderKt.parseArguments(JCommander.kt:14)
[Acceptance tests]    [detekt] 	at io.gitlab.arturbosch.detekt.cli.Main$Companion.parseArgumentsCheckingReportDirectory(Main.kt:87)
[Acceptance tests]    [detekt] 	at io.gitlab.arturbosch.detekt.cli.Main$Companion.main(Main.kt:78)
[Acceptance tests]    [detekt] 	at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt)
[Acceptance tests]    [detekt] Caused by: java.net.URISyntaxException: Illegal character in authority at index 7: file://C:\Jenkins\workspace\hes_enhancement_bump_detekt-ZXXJCVCLV6URFQ7ERNCH6PULFPARMMDBNRIPX4SZJF6HGEGM3TTA
[Acceptance tests]    [detekt] 	at java.net.URI$Parser.fail(URI.java:2848)
[Acceptance tests]    [detekt] 	at java.net.URI$Parser.parseAuthority(URI.java:3186)
[Acceptance tests]    [detekt] 	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
[Acceptance tests]    [detekt] 	at java.net.URI$Parser.parse(URI.java:3053)
[Acceptance tests]    [detekt] 	at java.net.URI.<init>(URI.java:588)
[Acceptance tests]    [detekt] 	at java.net.URI.create(URI.java:850)
[Acceptance tests]    [detekt] 	... 13 more
```

**Comment by arturbosch** [comment]
Jap, when trying to fix #115, I introduced another defekt. Later this week I install a virtualbox with Win10 and hopefully fix all Windows issues. For now maybe check if M11 works for you? CI with Windows works now but do not want to spam commits anymore and check appveyor all the time for each little change, waiting for my Windows copy ;)

**Comment by ovsyankin** [comment]
No worries. I've disabled detekt in that module for the time being.

**Comment by sschuberth** [comment]
@arturbosch Let me know if you need / want help with debugging Windows issues. But I do not want to duplicate any work you probably already have done (locally).

**Comment by arturbosch** [comment]
Thats kind of you, thx! Will point you to the PR to test it then :)

**Comment by arturbosch** [comment]
M12.2 will up in some minutes (after CI are green this tag). Can you please verify detekt now works for you ? Thx! :)

**Comment by ovsyankin** [comment]
In M12.2 the error seems to be fixed - I don't see the exception any more. Thanks!
