### ISSUE TITLE
Issues with Test configuration in IntelliJ

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#162]
Each time I'm working on detekt I'm having issues executing tests from IntelliJ. Generally tests run fine when executing them directly via Gradle in the command line, but when executing them in IntelliJ the test fails before it even begins running.

Is there any configuration I'm missing in my IntelliJ setup?

The tests fail with the following error:
```
Exception in thread "main" org.junit.platform.commons.util.PreconditionViolationException: Could not load class with name: io.gitlab.arturbosch.detekt.rules.performance.ForEachOnRangeSpec
	at org.junit.platform.engine.discovery.ClassSelector.lambda$getJavaClass$0(ClassSelector.java:71)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.junit.platform.engine.discovery.ClassSelector.getJavaClass(ClassSelector.java:70)
	at org.jetbrains.spek.engine.SpekTestEngine.resolveSpecs(SpekTestEngine.kt:79)
	at org.jetbrains.spek.engine.SpekTestEngine.discover(SpekTestEngine.kt:50)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:115)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:87)
	at org.junit.platform.launcher.Launcher.execute(Launcher.java:93)
	at org.jetbrains.spek.tooling.runner.junit.JUnitPlatformSpekRunner.run(JUnitPlatformSpekRunner.kt:107)
	at org.jetbrains.spek.tooling.MainKt.main(Main.kt:58)
```

I've seen similar errors being reported on the Spek repo which currently don't have a resolution. @arturbosch how do you usually run and debug tests in detekt?

**Comment by arturbosch** [comment]
I do not have any problems in intellij. I assume you have the spek plugin installed?

I use gradle on commandline to run the tests and debug in intellij. Which intellij version do you run? (which kotlin version is bundled?)

**Comment by Mauin** [comment]
I'm running `IntelliJ IDEA 2017.1.5`. Kotlin plugin is `1.1.3-release-IJ2017.1-2`.
Spek plugin is installed.

I have also seen this issue on previous IntelliJ/Kotlin versions. Makes the development on detekt super hard if I cannot properly debug 😕

**Comment by arturbosch** [comment]
Hmm I just tested a new intellij-community edition + updates and install spek and everything works. (I did not delete my .idea folder)
Have you tried deleting all `.idea` folders and `Invalidate caches`?

**Comment by Mauin** [comment]
This is the issue on the spek repo: https://github.com/JetBrains/spek/issues/181

The last time I was working on detekt the trick with running `compileTestJava` before running spek tests from IntelliJ did work for me but now that also stopped working.

**Comment by Mauin** [comment]
Cleared the caches, removed `.idea` folders, reinstalled IntelliJ. Something seems to have worked, it now works fine for me. Thanks for the input @arturbosch 👍

**Comment by beenotung** [comment]
@Mauin I encounter this issue from time to time, able to work around this issue by removing .idea folder and .iml file (close project before removing them).
Then I am able to run the test after open the project from the recent project list (and after set up the source and test folder in project settings).

Next time if you meet the same issue, you can try this flow without reinstalling the IDE.
