### ISSUE TITLE
Broken upgrade from RC14 to RC15

### ISSUE THREAD

**Issue by pun-ky** [arturbosch/detekt#1686]
## Expected Behavior
Working upgrade from RC14 to RC15

## Observed Behavior

```
$ sh gradlew -S
> Task :detekt FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':detekt'.
> A problem occurred starting process 'command 'C:\Program Files\Java\jdk1.8.0_121\bin\java.exe''

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':detekt'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:151)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:148)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:141)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.StartSnapshotTaskInputsBuildOperationTaskExecuter.execute(StartSnapshotTaskInputsBuildOperationTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'C:\Program Files\Java\jdk1.8.0_121\bin\java.exe''
        at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:232)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:209)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:356)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        ... 6 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'C:\Program Files\Java\jdk1.8.0_121\bin\java.exe'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:97)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:70)
        ... 7 more
Caused by: java.io.IOException: Cannot run program "C:\Program Files\Java\jdk1.8.0_121\bin\java.exe" (in directory "C:\Users\krystian.panek\Projects\gradle-aem-plugin"): CreateProcess error=206, The filename or extension is too long
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 11 more
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 12 more


* Get more help at https://help.gradle.org

BUILD FAILED in 5s
7 actionable tasks: 1 executed, 1 from cache, 5 up-to-date
```

switching back to RC14 resolves problem

## Steps to Reproduce

n/a

## Context

previously working with RC14, tried to upgrade to RC15 without changing detekt.yml config

## Your Environment

* Version of detekt used: RC15
* Version of Gradle used (if applicable): 5.4.0
* Operating System and version: Windows 10
* Link to your project (if it's a public repository): https://github.com/Cognifide/gradle-aem-plugin/blob/master/buildSrc/build.gradle.kts#L11

**Comment by arturbosch** [comment]
@3flex highly possible to the Gradle plugins filters/input files change?
It's the windows filename limit...

**Comment by 3flex** [comment]
@pun-ky how long are the file paths that you're feeding to Gradle?

The number of files should not be an issue but if any file paths are longer than 260 characters that will cause this issue on Windows.

Unfortunately this is an existing Windows limitation (that Gradle doesn't have an official workaround for https://github.com/gradle/gradle/issues/1989) and it's now surfaced because of an internal change, however making this change internally allows for better functionality in future with type resolution supported properly by the Gradle plugin 

@arturbosch up to you if you want to revert the change but it will hold back the project (or may require some ugly workarounds - haven't looked into that).

**Comment by Tolriq** [comment]
Facing the same issue.

I have no file with path length > 260 (Or 248 for edge cases). Furthermore for windows you could have cheated that by appending \\?\ at the start of the filename to use unicode path.

**Comment by emartynov** [comment]
I just got similar on OSX: 
```

Caused by: java.io.IOException: Cannot run program "/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java" (in directory "/Users/eugenmartynov/Development/source/ing/lovebird-android"): error=7, Argument list too long
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 7 more
Caused by: java.io.IOException: error=7, Argument list too long
        ... 8 more

```

**Comment by 3flex** [comment]
I've just created a PR which will hopefully fix this by passing arguments to detekt in a file instead of passing all arguments on the command line and hitting these limits.

Would appreciate if this could be tested to see if it works on the projects that are now failing @emartynov @pun-ky @Tolriq, thanks

**Comment by pun-ky** [comment]
@3flex I just cloned your branch. Run command `sh gradlew publishToMavenLocal` and tried with version RC15 / assured having `mavenLocal()` in plugins repository and.... not helped ;(

**Comment by arturbosch** [comment]
@3flex we start a new process when calling detekt-cli, wouldn't calling the cli via reflection already help here?

**Comment by 3flex** [comment]
@pun-ky is your project public? I'd like to try and replicate the issue. Also to be extra sure that you were running the version built locally please check the build/tmp/detekt directory which should contain a file called <task name>.args which contains the arguments passed to detekt.

@arturbosch that's beyond my level of knowledge...

The other possibility is it's related to length of classpath passed to the javaexec, there were changes there as well. A "pathing jar" is apparently a workaround for that.

**Comment by dector** [comment]
Do you have plans to ship this fix as a part of `RC-16` or as a separate hotfix release for `RC-15`?

**Comment by 3flex** [comment]
@arturbosch an RC-16 to confirm the fix works as expected would be great. Right now it's "works for me" but we haven't had confirmation from others yet... It's possible it's not a true fix particularly on anyone running detekt on Java 1.8.

Also I know snapshot builds were pushed back, but this is a great example of where having them might have picked up the problem prior to release.

**Comment by arturbosch** [comment]
@dector yes RC16 will come soon.
I also currently read https://reflectoring.io/publish-snapshots-with-gradle/ and try to comeup with snapshots hosting ...

**Comment by arturbosch** [comment]
Though snapshots are real -> https://oss.jfrog.org/artifactory/oss-snapshot-local/io/gitlab/arturbosch/detekt/

**Comment by dector** [comment]
Awesome. Thank you!
