### ISSUE TITLE
InvalidBaselineState

### ISSUE THREAD

**Issue by ber4444** [arturbosch/detekt#1717]
```
Exception in thread "main" io.gitlab.arturbosch.detekt.cli.baseline.InvalidBaselineState: Error on position 1:1 while reading the baseline xml file!
        at io.gitlab.arturbosch.detekt.cli.baseline.BaselineFormat.read(BaselineFormat.kt:25)
        at io.gitlab.arturbosch.detekt.cli.baseline.BaselineFacade.<init>(BaselineFacade.kt:18)
        at io.gitlab.arturbosch.detekt.cli.OutputFacade.<init>(OutputFacade.kt:22)
        at io.gitlab.arturbosch.detekt.cli.runners.Runner.execute(Runner.kt:23)
        at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:24)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
```

## Your Environment
* Version of detekt used:'1.0.0-RC15'
* Version of Gradle used (if applicable):5.4.1
* Operating System and version:Mojave OS X
Kotlin 1.3.40

**Comment by cortinico** [comment]
Hey @ber4444 
Can you please copy over the content of your baseline file?
Apparently the problem might be related to the parser used to read the baseline.
The first character in the baseline must be a `<` (not a space or a new line).

**Comment by ber4444** [comment]
@cortinico 
This error happens every time I use an yml file instead of xml.
Note that gradle detektGenerateConfig actually generates an yml as also documented at https://arturbosch.github.io/detekt/

**Comment by ber4444** [comment]
YML starts with:
```
build:
  maxIssues: 10
  weights: .....
```
while XML starts with:
```
<?xml version="1.0" ?>
<SmellBaseline>....
```

**Comment by cortinico** [comment]
@ber4444 
I think you're mixing up the baseline files and configuration file.

The configuration file is generated by `detektGenerateConfig` and is used to configure which rules should run and all the parameters. This must be a Yaml file.

The baseline file is generated by `detektBaseline` and is used to have a _snapshots_ of all the issues that will be ignored by subsequent builds. Useful when you're enabling a new rule or setting up detekt for the first time. More info here: https://arturbosch.github.io/detekt/baseline.html
