### ISSUE TITLE
HtmlReport error in rule: ParameterListWrapping

### ISSUE THREAD

**Issue by bjarneheden** [arturbosch/detekt#2218]
I found an error in the html report:
- Rule: ParameterListWrapping
- Detetk version: 1.3.1
- Stacktrace:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 8
	at java.lang.String.substring(String.java:1963)
	at io.gitlab.arturbosch.detekt.cli.out.HtmlUtilsKt.writeErrorLine(HtmlUtils.kt:51)
	at io.gitlab.arturbosch.detekt.cli.out.HtmlUtilsKt.access$writeErrorLine(HtmlUtils.kt:1)
	at io.gitlab.arturbosch.detekt.cli.out.HtmlUtilsKt$snippetCode$1$1.invoke(HtmlUtils.kt:35)
	at io.gitlab.arturbosch.detekt.cli.out.HtmlUtilsKt$snippetCode$1$1.invoke(HtmlUtils.kt)
```
- How to reproduce it: <WRITE HERE HOW TO REPRODUCE THIS ISSUE. A CODE SNIPPET IS THE BEST WAY.>

**Comment by schalkms** [comment]
May I ask you to provide the code that gets flagged by the `ParameterListWrapping` rule? This helps us to reproduce the problem.

**Comment by schalkms** [comment]
Closed, because we couldn't reproduce the problem without any context or code.
