### ISSUE TITLE
RuleSetProvider: Error reading configuration file

### ISSUE THREAD

**Issue by r4zzz4k** [arturbosch/detekt#2411]
## Expected Behavior
Running `./gradlew detekt` on detekt itself should not fail with exception.

## Observed Behavior
Running `./gradlew detekt` sometimes returns the following:
```
Ignoring listeners of task graph ready event, as this build (:detekt-gradle-plugin) has already executed work.
> Task :detekt-api:detekt FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':detekt-api:detekt'.
> io.gitlab.arturbosch.detekt.api.RuleSetProvider: Error reading configuration file
```
Stacktrace provides a bit of additional information:
```
Caused by: java.util.ServiceConfigurationError: io.gitlab.arturbosch.detekt.api.RuleSetProvider: Error reading configuration file
        at io.gitlab.arturbosch.detekt.core.RuleSetLocator.load(RuleSetLocator.kt:29)
        at io.gitlab.arturbosch.detekt.cli.config.DefaultPropertiesConfigValidator$validate$1.invoke(DefaultPropertiesConfigValidator.kt:20)
        at io.gitlab.arturbosch.detekt.cli.config.DefaultPropertiesConfigValidator.validate(DefaultPropertiesConfigValidator.kt:27)
        at io.gitlab.arturbosch.detekt.cli.config.ConfigValidatorsKt.checkConfiguration(ConfigValidators.kt:18)
        at io.gitlab.arturbosch.detekt.cli.runners.Runner.execute(Runner.kt:30)
        at io.gitlab.arturbosch.detekt.invoke.DefaultCliInvoker.invokeCli(DetektInvoker.kt:51)
        ... 93 more
Caused by: java.util.zip.ZipException: invalid distance too far back
        ... 99 more
```

## Steps to Reproduce
I'm not sure it's reproducable 100% of times, but still:
1. Clone PR branch for #2410
2. Checkout it's parrent commit (4ea5873)
3. Run `./gradlew detekt` (should work as expected)
4. Checkout PR branch
5. Run ./gradlew detekt`

## Context
I'm trying to contribute to the project, and I'm unable to walk through steps of contribution guildelines.

## Your Environment
* Version of detekt used: 1.7.0-beta1 (master branch, ref 4ea5873)
* Version of Gradle used (if applicable): 6.2.1
* Operating System and version: Ubuntu 19.10
* Java version just in case:
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
```

**Comment by schalkms** [comment]
Does this also occur with a state before the mentioned commit 4ea5873 ?

**Comment by r4zzz4k** [comment]
Yes, that's exactly what happened. I've rebased my branch onto fresh master from several commits earlier. That explains why I was able to see `detekt` results earlier and then started to get the error. Didn't try stopping the daemon. After reboot it's working again, so that's most probably it.

**Comment by arturbosch** [comment]
@r4zzz4k thanks for the insights.
I will close this for now.

**Comment by sanghaimuskan** [comment]
@arturbosch  I am still getting this error, I have tried doing gradle --stop. but still getting the same error
