### ISSUE TITLE
HtmlReport error in rule: NoEmptyClassBody

### ISSUE THREAD

**Issue by dudeck** [arturbosch/detekt#2438]
I found an error in the html report:
- Rule: NoEmptyClassBody
- Detetk version: 1.5.1
- Stacktrace:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 45
	at java.lang.String.substring(String.java:1963)
	at io.gitlab.arturbosch.detekt.cli.out.HtmlUtilsKt.writeErrorLine(HtmlUtils.kt:51)
	at io.gitlab.arturbosch.detekt.cli.out.HtmlUtilsKt.access$writeErrorLine(HtmlUtils.kt:1)
	at io.gitlab.arturbosch.detekt.cli.out.HtmlUtilsKt$snippetCode$1$1.invoke(HtmlUtils.kt:35)
	at io.gitlab.arturbosch.detekt.cli.out.HtmlUtilsKt$snippetCode$1$1.invoke(HtmlUtils.kt)
```
- How to reproduce it: <WRITE HERE HOW TO REPRODUCE THIS ISSUE. A CODE SNIPPET IS THE BEST WAY.>

**Comment by BraisGabin** [comment]
Thanks for report this! Could you check if this error appears using `1.7.0-beta2`? We did some fixes to avoid this problem.

**Comment by schalkms** [comment]
Yeah, without the code in hand it's nearly impossible to reproduce the problem.
