### ISSUE TITLE
FileSystemNotFoundException in detekt 1.7.0 when using --config-resource

### ISSUE THREAD

**Issue by josephlbarnett** [arturbosch/detekt#2503]
## Expected Behavior
the config from a jar in the classpath should be used

## Observed Behavior
```
java.nio.file.FileSystemNotFoundException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:169)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:155)
	at java.base/java.nio.file.Path.of(Path.java:208)
	at java.base/java.nio.file.Paths.get(Paths.java:97)
	at io.gitlab.arturbosch.detekt.rules.documentation.LicenceHeaderLoaderExtension.init(LicenceHeaderLoaderExtension.kt:27)
	at io.gitlab.arturbosch.detekt.core.FileProcessorLocator.load(FileProcessorLocator.kt:18)
	at io.gitlab.arturbosch.detekt.core.DetektFacade$Companion.create(DetektFacade.kt:90)
	at io.gitlab.arturbosch.detekt.cli.runners.Runner.execute(Runner.kt:33)
	at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:20)
```

## Steps to Reproduce
* include a detekt-config.yml in a jar that you put in the `-classpath` of the detekt cli
* run `java -classpath .... io.gitlab.arturbosch.detekt.cli.Main --input /path/to/src/main/kotlin --config-resource detekt-config.yml`

## Context
We include our detekt-config in a jar that we pull in via maven and run detekt via antrun plugin,b ut the above cli invokation shows the same issue.  Works fine in 1.6.0 but not in 1.7.0.

## Your Environment

* Version of detekt used: 1.7.0
* Version of Gradle used (if applicable): --
* Operating System and version: circle ci linux container
* Link to your project (if it's a public repository): 
https://app.circleci.com/jobs/github/trib3/leakycauldron/849 <-- failed build
https://github.com/trib3/leakycauldron/blob/master/parent-pom/pom.xml#L1302-L1344 <-- maven config

**Comment by josephlbarnett** [comment]
https://stackoverflow.com/questions/25032716/getting-filesystemnotfoundexception-from-zipfilesystemprovider-when-creating-a-p appears to show a solution to this
