### ISSUE TITLE
ClassNotFoundException: com.beust.jcommander.ParameterException

### ISSUE THREAD

**Issue by sschuberth** [arturbosch/detekt#2518]
## Expected Behavior
*detekt* should not throw `ClassNotFoundException`.

## Observed Behavior
*detekt* throws

```
Caused by: java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException
        at io.gitlab.arturbosch.detekt.invoke.DefaultCliInvoker.invokeCli(DetektInvoker.kt:46)
        at io.gitlab.arturbosch.detekt.Detekt.check(Detekt.kt:215)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
```

See
https://travis-ci.com/github/oss-review-toolkit/ort/builds/155601325#L912

## Steps to Reproduce
Checkout https://github.com/oss-review-toolkit/ort/pull/2409 and run `./gradlew detekt`.

## Context
What surprises me is that JCommander is used in the Gradle plugin. What does the plugin need CLI parsing for?

## Your Environment

* Version of detekt used: 1.7.1
* Version of Gradle used (if applicable): 6.2.2
* Operating System and version: Linux / Windows
* Link to your project (if it's a public repository): https://github.com/oss-review-toolkit/ort/tree/update-dependencies

**Comment by sschuberth** [comment]
Turns out this is actually the same as https://github.com/arturbosch/detekt/issues/2518.
