### ISSUE TITLE
Detekt Gradle plugin breaks the Gradle properties task

### ISSUE THREAD

**Issue by uglyog** [arturbosch/detekt#349]
Running the Gradle properties task with detekt plugin fails.

Stacktrace:

```
Caused by: java.lang.reflect.InvocationTargetException
        at kotlin.reflect.jvm.internal.FunctionCaller$Method.callMethod(FunctionCaller.kt:98)
        at kotlin.reflect.jvm.internal.FunctionCaller$InstanceMethod.call(FunctionCaller.kt:115)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:107)
        at kotlin.reflect.jvm.internal.KProperty1Impl.get(KProperty1Impl.kt:33)
        at io.gitlab.arturbosch.detekt.extensions.ReflectionUtilsKt$reflectiveToString$properties$1.invoke(ReflectionUtils.kt:11)
        at io.gitlab.arturbosch.detekt.extensions.ReflectionUtilsKt$reflectiveToString$properties$1.invoke(ReflectionUtils.kt)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:135)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:96)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:119)
        at kotlin.sequences.SequencesKt___SequencesKt.joinTo(_Sequences.kt:1290)
        at kotlin.sequences.SequencesKt___SequencesKt.joinToString(_Sequences.kt:1308)
        at kotlin.sequences.SequencesKt___SequencesKt.joinToString$default(_Sequences.kt:1307)
        at io.gitlab.arturbosch.detekt.extensions.ReflectionUtilsKt.reflectiveToString(ReflectionUtils.kt:13)
        at io.gitlab.arturbosch.detekt.extensions.DetektExtension.toString(DetektExtension.kt:78)
        at org.gradle.internal.logging.text.AbstractStyledTextOutput.format(AbstractStyledTextOutput.java:47)
        at org.gradle.internal.logging.text.AbstractStyledTextOutput.formatln(AbstractStyledTextOutput.java:58)
        at org.gradle.api.tasks.diagnostics.internal.PropertyReportRenderer.addProperty(PropertyReportRenderer.java:30)
        at org.gradle.api.tasks.diagnostics.PropertyReportTask.generate(PropertyReportTask.java:48)
        at org.gradle.api.tasks.diagnostics.AbstractReportTask$2.generateReport(AbstractReportTask.java:74)
        at org.gradle.api.tasks.diagnostics.internal.ReportGenerator.generateReport(ReportGenerator.java:58)
        at org.gradle.api.tasks.diagnostics.AbstractReportTask.generate(AbstractReportTask.java:84)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        ... 39 more
Caused by: java.lang.IllegalArgumentException: Make sure the idea path is specified to run idea tasks!
        at io.gitlab.arturbosch.detekt.extensions.IdeaExtension.formatArgs(IdeaExtension.kt:14)
        at io.gitlab.arturbosch.detekt.extensions.DetektExtension.getIdeaFormatArgs(DetektExtension.kt:17)
        ... 61 more

```

**Comment by arturbosch** [comment]
Hi, thanks for reporting!
Looks like gradle invokes the toString method on tasks for diagnostic reasons ... this will come to the next release :).
