### ISSUE TITLE
Rule causes files to be appended to themselves 

### ISSUE THREAD

**Issue by snowe2010** [arturbosch/detekt#430]
Per a conversation on gitter with @schalkms this code

```kotlin
class PrivateVariablesInTest(config: Config = Config.empty) : Rule(config) {
    override val issue = Issue(javaClass.simpleName, Severity.Style, "", Debt.FIVE_MINS)

    override fun visitProperty(property: KtProperty) {
        println("${property.name} ${property.isLocal}")
        if (!property.isPrivate() && !property.isLocal) {
            report(CodeSmell(issue, Entity.from(property)))
            withAutoCorrect {
                property.addModifier(KtModifierKeywordToken.keywordModifier(KtTokens.PRIVATE_KEYWORD.value))
            }
        }
    }
}
```

causes the error

```
> java -jar detekt-cli/build/libs/detekt-cli-1.0.0.RC4-3-all.jar -o ../server -on kotlinreports -c default-detekt-config.yml -i ../server/lp-server-read/src/test/java/com/promontech/calculator/applicant/MonthlyAverageCalculatorTest.kt --format -p detekt-formatting/build/libs/detekt-formatting-1.0.0.RC4-3.jar
Analyzing 1 kotlin files: .
Exception in thread "main" java.nio.file.FileSystemException: ../server/lp-server-read/src/test/java/com/company/calculator/applicant/MonthlyAverageCalculatorTest.kt/../server/lp-server-read/src/test/java/com/company/calculator/applicant/MonthlyAverageCalculatorTest.kt: Not a directory
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
    at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
    at java.nio.file.Files.newOutputStream(Files.java:216)
    at java.nio.file.Files.write(Files.java:3292)
    at io.gitlab.arturbosch.detekt.core.KtFileModifier.saveModifiedFiles(KtFileModifier.kt:22)
    at io.gitlab.arturbosch.detekt.core.Detektor$run$1.invoke(Detektor.kt:40)
    at io.gitlab.arturbosch.detekt.core.Detektor$run$1.invoke(Detektor.kt:16)
    at io.gitlab.arturbosch.detekt.core.TasksKt.withExecutor(Tasks.kt:14)
    at io.gitlab.arturbosch.detekt.core.Detektor.run(Detektor.kt:26)
    at io.gitlab.arturbosch.detekt.core.Detektor.run(Detektor.kt:24)
    at io.gitlab.arturbosch.detekt.core.Detektor.run$default(Detektor.kt:24)
    at io.gitlab.arturbosch.detekt.cli.Runner.execute(Runner.kt:19)
    at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:19)
```

**Comment by snowe2010** [comment]
Files are appended to themselves due to `project` being the same path as `it.first` at https://github.com/arturbosch/detekt/blob/master/detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/KtFileModifier.kt#L19

`.map { project.resolve(it.first) to it.second }`

**Comment by schalkms** [comment]
Okay. Would you mind to create another PR after inspecting this? Thank you! 👍

**Comment by snowe2010** [comment]
@schalkms how should I even resolve that? I don't understand what `project.resolve(it.first)` was trying to accomplish. I can just map `it.first to it.second` and that would work, but not sure why `project` is even being passed in then

**Comment by schalkms** [comment]
Ok. I think @arturbosch should give feedback what he was trying to accomplish there. Thank you for reporting your inspections so far! 👍

**Comment by arturbosch** [comment]
The PSI lib does not handle relative paths as needed (or I just don't understand it), so I relativized the paths (needed elsewhere) and put them together for the saving. Ofc if we only analyze one file this code breaks as it expects a directory as project. Maybe the code should use the absolute path provided by the PSI.
Will look at this.

**Comment by arturbosch** [comment]
I could not reproduce the issue. Please wrap your code into a jar so I can use it as a plugin and debug the behavior.

For documentation this is what I tried:

```kotlin
class PrivateVariablesInTest(config: Config = Config.empty) : Rule(config) {
	override val issue = Issue(javaClass.simpleName, Severity.Style, "", Debt.FIVE_MINS)

	override fun visitProperty(property: KtProperty) {
		println("${property.name} ${property.isLocal}")
		if (!property.isPrivate() && !property.isLocal) {
			report(CodeSmell(issue, Entity.from(property)))
			withAutoCorrect {
				property.addModifier(KtModifierKeywordToken.keywordModifier(KtTokens.PRIVATE_KEYWORD.value))
			}
		}
	}
}

class TestProvider : RuleSetProvider {
	override val ruleSetId: String = "bla"

	override fun instance(config: Config): RuleSet {
		return RuleSet(ruleSetId, listOf(PrivateVariablesInTest(config)))
	}

}

class PrivateVariableInTestTest {

	@Test
	fun stuff() {
		val path = Case.CasesFolder.path().resolve("Test.kt")
		val settings = ProcessingSettings(path, excludeDefaultRuleSets = true)
		val detektor = DetektFacade.instance(settings, listOf(TestProvider()), emptyList())
		detektor.run()
	}
}
class Test3 {
	val s = ""
}
```

**Comment by snowe2010** [comment]
@arturbosch was it maybe the command I was using to run it?

**Comment by arturbosch** [comment]
Looks ok. You wrote your rule in the formatting package? Please append the resulting jar here so I can debug it ^^

**Comment by snowe2010** [comment]
I am unable to reproduce what was happening now. Closing until I can reproduce it again. Sorry for the trouble.
