### ISSUE TITLE
ExceptionInInitializerError with 1.0.0.RC5-5

### ISSUE THREAD

**Issue by juergenzimmermann** [arturbosch/detekt#566]
After upgrading from 1.0.0.RC5-4 to 1.0.0.RC5-5 I'm getting the following stacktrace when running "gradle detektCheck". I'm using Kotlin 1.2.0-rc-39 and Java 9.0.1.

```
> Task :detektCheck FAILED
Exception in thread "main" java.lang.ExceptionInInitializerError
        at io.gitlab.arturbosch.detekt.core.KtCompiler.<init>(KtCompiler.kt:17)
        at io.gitlab.arturbosch.detekt.core.KtTreeCompiler.<init>(KtTreeCompiler.kt:15)
        at io.gitlab.arturbosch.detekt.core.KtTreeCompiler$Companion.instance(KtTreeCompiler.kt:23)
        at io.gitlab.arturbosch.detekt.core.Detektor.run$default(Detektor.kt:25)
        at io.gitlab.arturbosch.detekt.cli.Runner.execute(Runner.kt:20)
        at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:19)
Caused by: java.lang.IllegalStateException: LOGGING: Loading modules: [java.se, javafx.base, javafx.controls, javafx.fxml, javafx.graphics, javafx.media, javafx.swing, javafx.web, jdk.accessibility, jdk.attach, jdk.compiler, jdk.dynalink, jdk.httpserver, jdk.incubator.httpclient, jdk.jartool, jdk.javadoc, jdk.jconsole, jdk.jdi, jdk.jfr, jdk.jshell, jdk.jsobject, jdk.management, jdk.management.cmm, jdk.management.jfr, jdk.management.resource, jdk.net, jdk.packager, jdk.packager.services, jdk.plugin.dom, jdk.scripting.nashorn, jdk.sctp, jdk.security.auth, jdk.security.jgss, jdk.unsupported, jdk.xml.dom, oracle.desktop, oracle.net, java.base, java.rmi, java.sql, java.xml, java.logging, java.scripting, java.datatransfer, java.compiler, java.xml.crypto, java.prefs, java.sql.rowset, java.naming, java.desktop, java.management.rmi, java.management, java.security.sasl, java.instrument, java.security.jgss, jdk.internal.jvmstat, jdk.management.agent, jdk.jdwp.agent, jdk.internal.ed, jdk.internal.opt, jdk.internal.le, jdk.jdeps, jdk.jlink] (no MessageCollector configured)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.report(ClasspathRootsResolver.kt:314)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.report$default(ClasspathRootsResolver.kt:312)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.addModularRoots(ClasspathRootsResolver.kt:254)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.computeRoots(ClasspathRootsResolver.kt:124)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:79)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:223)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:114)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:401)
        at io.gitlab.arturbosch.detekt.api.ProjectExtensionKt.<clinit>(ProjectExtension.kt:20)
        ... 6 more
```

**Comment by arturbosch** [comment]
Looks like a java9-kotlin-compiler-incompatibility ...
Did you used the same versions with 1.0.0.RC5-4?

**Comment by juergenzimmermann** [comment]
@arturbosch Yes, I used both Kotlin 1.2.0-rc-39 and Java 9.0.1.

**Comment by Mauin** [comment]
I'm not seeing any issues in a project with Kotlin v1.1.60 and the latest JDK 1.8.0_152.

**Comment by arturbosch** [comment]
Me too @Mauin, but the kotlin compiler now does some magic for java9 modules inside `KotlinEnvironment` ... need to reproduce that combination for myself.

**Comment by juergenzimmermann** [comment]
@arturbosch Is there a way to go back to 1.0.0.RC5-4? When I just set the plugin's version back to 1.0.0.RC5-4, the new JARs are still used.

**Comment by arturbosch** [comment]
Try 
```
detekt {
  version = '1.0.0.RC5-4'
  ...
}
```

**Comment by juergenzimmermann** [comment]
Thank you @arturbosch setting the version inside the detekt task works fine.

**Comment by juergenzimmermann** [comment]
FYI, setting the plugin version to 1.0.0.RC5-**5**, and the task's version to 1.0.0.RC5-**4** works fine with Java 9.0.1 and Kotlin 1.2.0-rc-39

**Comment by arturbosch** [comment]
Thanks for the info. The only thing that could have lead to this error is:
Update to Kotlin 1.1.60 - [#546](https://github.com/arturbosch/detekt/pull/546)

We haven't touched any core classes, just rules.

**Comment by juergenzimmermann** [comment]
Same issue with Kotlin 1.2.0-rc-**84** and detekt  1.0.0.RC5-**5**.

**Comment by Mauin** [comment]
Can repro this by running `gradle detektCheck` on the detekt codebase with JDK 9.0.1.

**Comment by arturbosch** [comment]
Yep, can confirm this too. Imo its a kotlin-compiler error dealing with java9. 
Some months ago we had already problems with java9 because of an module dependency of `javax.bind`. 
I'm pretty sure that the code in `KotlinCoreEnvironment` for modules is new. Back then java9 worked after changing the xml dependencies

**Comment by juergenzimmermann** [comment]
The issue still exists with RC5-6

**Comment by juergenzimmermann** [comment]
Same exception with RC6 and Kotlin 1.2.10

**Comment by arturbosch** [comment]
I've created an issue at kotlin [issue tracker](https://youtrack.jetbrains.com/issue/KT-21995)

**Comment by arturbosch** [comment]
@juergenzimmermann hey, I've fixed the java9 issue :). Could you please test the branch build with your setup? Thanks!

**Comment by juergenzimmermann** [comment]
@arturbosch I cloned the `detekt` repo, switched to the branch `java9-changes`, invoked `./gradlew build shadowJar` and finally invoked `java -jar detekt-cli/build/libs/detekt-cli-1.0.0.RC6-all.jar -i C:\path\to\my\project`: Everything works fine. Thank you very much!
Now I'm waiting for the next release ;-)

**Comment by juergenzimmermann** [comment]
@arturbosch Confirmed: The issue is gone when using RC6-1
