### ISSUE TITLE
1.0.0-RC5-5 org.jetbrains.kotlin.psi.KtProperty cannot be cast to org.jetbrains.kotlin.psi.KtClassOrObject

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#568]
> Analyzing 19 kotlin files: ............Exception in thread "main" java.util.concurrent.CompletionException: java.lang.ClassCastException: org.jetbrains.kotlin.psi.KtProperty cannot be cast to org.jetbrains.kotlin.psi.KtClassOrObject
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: org.jetbrains.kotlin.psi.KtProperty cannot be cast to org.jetbrains.kotlin.psi.KtClassOrObject
        at io.gitlab.arturbosch.detekt.rules.style.SpacingBetweenPackageAndImports.checkKtElementsDeclaration(SpacingBetweenPackageAndImports.kt:47)
        at io.gitlab.arturbosch.detekt.rules.style.SpacingBetweenPackageAndImports.visitImportList(SpacingBetweenPackageAndImports.kt:27)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitImportList(KtVisitorVoid.java:531)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitImportList(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtImportList.accept(KtImportList.java:38)
        at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:58)
        at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
        at org.jetbrains.kotlin.com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:861)
        at org.jetbrains.kotlin.psi.KtTreeVisitorVoid.visitElement(KtTreeVisitorVoid.java:25)
        at org.jetbrains.kotlin.com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
        at org.jetbrains.kotlin.psi.KtVisitor.visitKtFile(KtVisitor.java:73)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:69)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:513)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:221)
        at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:207)
        at io.gitlab.arturbosch.detekt.api.BaseRule.visit(BaseRule.kt:24)
        at io.gitlab.arturbosch.detekt.api.BaseRule.visitFile(BaseRule.kt:18)
        at io.gitlab.arturbosch.detekt.api.RuleSet.accept(RuleSet.kt:20)
        at io.gitlab.arturbosch.detekt.core.Detektor.analyze(Detektor.kt:60)
        at io.gitlab.arturbosch.detekt.core.Detektor.access$analyze(Detektor.kt:16)
        at io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:33)
        at io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:16)
        at io.gitlab.arturbosch.detekt.core.TasksKt$runAsync$1.invoke(Tasks.kt:20)
        at io.gitlab.arturbosch.detekt.core.TasksKt$task$1.get(Tasks.kt:24)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)

This does not happen with RC5-4. Unfotunately I can't pin point the exact file where is is thrown.

**Comment by arturbosch** [comment]
Args thanks for reporting, looks like an easy fix:

changing `val name = (ktElements.first() as KtClassOrObject).name ?: "the class or object"`
to `val name = (ktElements.first() as? KtClassOrObject)?.name ?: "the class or object"`

**Comment by vanniktech** [comment]
Then I'm surprised `(ktElements.first() as KtClassOrObject).name` was not caught by detekt itself. I remember that there is a rule `UnsafeCast` or something like that which should catch this case. Or is it turned off?

**Comment by arturbosch** [comment]
Yes it would have found it. It is not turned on because it was a new rule when we said all new rules are default false and because we have like 20+ findings of UnsafeCast for `Config` and kotlin compiler specific things ... will see how to work with that.

**Comment by aochsner** [comment]
Hmmm i'm still getting this error in RC5-6

**Comment by aochsner** [comment]
Seems to work for me but had to specifically set `detekt.version` to latest (RC5-6 ATM).  Not sure why might have had cached RC5-5?

**Comment by arturbosch** [comment]
No Idea, maybe jcenter needs some time tomorrow provide the right information?
