### ISSUE TITLE
Updating beyond RC5-3 breaks the build

### ISSUE THREAD

**Issue by rock3r** [arturbosch/detekt#585]
My setup: Gradle 4.3.1, Android Gradle Plugin 3.0.1, Kotlin 1.2.0.

I tried upgrading Detekt from `1.0.0.RC5-3` to `1.0.0.RC5-6`, but any version beyond `RC5-3` breaks the build with this message:

```
FAILURE: Build failed with an exception.

* What went wrong:
org.jetbrains.kotlin.cli.common.arguments.K2JVMCompilerArguments.setAllWarningsAsErrors(Z)V

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.NoSuchMethodError: org.jetbrains.kotlin.cli.common.arguments.K2JVMCompilerArguments.setAllWarningsAsErrors(Z)V
        at org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptionsBaseKt.fillDefaultValues(KotlinJvmOptionsBase.kt:84)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.setupCompilerArgs(Tasks.kt:285)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.setupCompilerArgs(Tasks.kt:242)
        at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.setupCompilerArgs$default(Tasks.kt:220)
        at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.getSerializedCompilerArguments(Tasks.kt:115)
        at org.jetbrains.kotlin.gradle.internal.KaptGenerateStubsTask_Decorated.getSerializedCompilerArguments(Unknown Source)
        at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo$2.create(TaskPropertyInfo.java:88)
        at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:230)
        at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo.getValue(TaskPropertyInfo.java:85)
        at org.gradle.api.internal.tasks.TaskPropertyValue.validate(TaskPropertyValue.java:38)
        at org.gradle.api.internal.tasks.DefaultTaskInputPropertySpec.validate(DefaultTaskInputPropertySpec.java:53)
        at org.gradle.api.internal.tasks.DefaultTaskInputs.validate(DefaultTaskInputs.java:168)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:47)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
```

#### Repro steps

 1. Clone [Squanchy-Android `@update-stuff`](https://github.com/squanchy-dev/squanchy-android/tree/update_stuff)
 2. Open the root `build.gradle` and upgrade the Detekt plugin to any version higher than `1.0.0.RC5-3`, on line 20
 3. `$ ./gradlew build`
 4. Observe the aforementioned error

Leaving Detekt to `1.0.0.RC5-3` makes the `build` succeed. Same issue happens with a `clean build` with `RC5-4`+.

**Comment by arturbosch** [comment]
That sounds not good ...

**Comment by rock3r** [comment]
Ah yeah you need to create some values in the `team-props` folder. There's a bunch of `*.properties.sample` files, rename them to `*.properties` and put some random values in there.

**Comment by arturbosch** [comment]
Ok, will try to check it soon!

**Comment by rock3r** [comment]
I tried looking into it but I am not exactly sure what the issue is :(

**Comment by asos-davidf** [comment]
Same error in my project, the logs don't say much and the stacktrace doesn't involve code from detekt though...

**Comment by rock3r** [comment]
I don't have the issue anymore since RC6, should we close this?

**Comment by arturbosch** [comment]
Great! I will close it for now. Maybe if @asos-davidf still encounters the error, we can reopen it.

**Comment by asos-davidf** [comment]
RC6-2 is looking good for me too, nice!

**Comment by arturbosch** [comment]
Nice!
