### ISSUE TITLE
Failed to initialize native filesystem for Windows

### ISSUE THREAD

**Issue by sschuberth** [arturbosch/detekt#630]
Running detekt 1.0.0.RC5-6 on Windows gives bogus warnings:

        WARN: Failed to initialize native filesystem for Windows
        java.lang.RuntimeException: Could not find installation home path. Please make sure bin/idea.properties is present in the installation directory.
                at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:97)
                at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.findBinFile(PathManager.java:173)
                at org.jetbrains.kotlin.com.intellij.util.lang.UrlClassLoader.loadPlatformLibrary(UrlClassLoader.java:320)
                at org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32.<clinit>(IdeaWin32.java:48)
                at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUtil.java:77)
                at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.java:69)
                at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.setFileStampAndLength(ZipHandler.java:69)
                at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:51)
                at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:47)
                at org.jetbrains.kotlin.com.intellij.util.io.FileAccessorCache.createHandle(FileAccessorCache.java:66)
                at org.jetbrains.kotlin.com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:52)
                at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.getCachedZipFileHandle(ZipHandler.java:112)
                at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.createEntriesMap(ZipHandler.java:87)
                at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ArchiveHandler.getEntriesMap(ArchiveHandler.java:190)
                at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarHandler.<init>(CoreJarHandler.java:42)
                at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem$1.create(CoreJarFileSystem.java:37)
                at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem$1.create(CoreJarFileSystem.java:33)
                at org.jetbrains.kotlin.com.intellij.util.containers.FactoryMap.get(FactoryMap.java:58)
                at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.findFileByPath(CoreJarFileSystem.java:50)
                at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.findJarRoot(KotlinCoreEnvironment.kt:352)
                at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.contentRootToVirtualFile(KotlinCoreEnvironment.kt:333)
                at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.access$contentRootToVirtualFile(KotlinCoreEnvironment.kt:114)
                at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$4.invoke(KotlinCoreEnvironment.kt:216)
                at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$4.invoke(KotlinCoreEnvironment.kt:114)
                at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:70)
                at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:223)
                at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:114)
                at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:401)
                at io.gitlab.arturbosch.detekt.api.ProjectExtensionKt.<clinit>(ProjectExtension.kt:20)
                at io.gitlab.arturbosch.detekt.core.KtCompiler.<init>(KtCompiler.kt:17)
                at io.gitlab.arturbosch.detekt.core.KtTreeCompiler.<init>(KtTreeCompiler.kt:15)
                at io.gitlab.arturbosch.detekt.core.KtTreeCompiler$Companion.instance(KtTreeCompiler.kt:23)
                at io.gitlab.arturbosch.detekt.core.Detektor.run$default(Detektor.kt:25)
                at io.gitlab.arturbosch.detekt.cli.Runner.execute(Runner.kt:20)
                at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:19)

The task still succeeds though (if no violations are found, of course).

**Comment by arturbosch** [comment]
I've asked about this message in the compiler slack channel. Will update the issue ^^

**Comment by 3flex** [comment]
I found a workaround while working on #485 - I used `System.setProperty("idea.io.use.fallback", "true")`, called before `KotlinCoreEnvironment.createForProduction`. This came from dokka.

Change should go in `detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/ProjectExtension.kt` (I'd submit a PR but not using a machine I can test this on).

The check is trigged in https://github.com/JetBrains/intellij-community/blob/master/platform/util/src/com/intellij/openapi/util/io/win32/IdeaWin32.java - based on this, might be better to use the more specific `System.setProperty("idea.use.native.fs.for.win", "false")`.

**Comment by sschuberth** [comment]
Thanks, but for me the question is *why* would you need to set `idea.use.native.fs.for.win` to `false`? I mean, leaving this to `true` sounds like a good thing, no?

**Comment by 3flex** [comment]
The Kotlin compiler uses many components from IntelliJ's OpenAPI, and it seems this code path, as it stands, tries loading IdeaWin32.dll from IntelliJ. It's checking for the IntelliJ home path first, since it will expect the file to be in the IntelliJ folder, and this is the check that's failing and triggering the error.

So unless detekt requires IntelliJ to be installed to work without a warning on Windows (not practical) or bundles the DLL then detekt can work OK and just ensure the warning doesn't display.

As you said detekt still checks the files OK and flags violations when it sees them so if this issue is just about removing the warning, this would be the way to go.

**Comment by arturbosch** [comment]
Cool thanks for the enlightening :), if dokka is doing it, then it will be ok! Thanks for the PR soon :).

**Comment by sschuberth** [comment]
Thanks for the explanation, @3flex. Out of curiosity, any idea what change in detekt triggered using that code path? As that started happening only quite recently.

**Comment by 3flex** [comment]
I noticed that it only started happening recently as well (also on Windows). No idea why - might have been an internal change in the Kotlin compiler.

**Comment by arturbosch** [comment]
@sschuberth do you might testing #634 for us please?

**Comment by sschuberth** [comment]
@arturbosch I can confirm that it makes the

    WARN: Failed to initialize native filesystem for Windows

warning go away on Windows.
