### ISSUE TITLE
ExceptionInInitializerError with Kotlin 1.2.30-eap-47 and Java 10b43

### ISSUE THREAD

**Issue by juergenzimmermann** [arturbosch/detekt#747]
When using _detekt 1.0.0.RC6-3_ with _Kotlin 1.2.30-eap-47_ and _JDK 10b43_ I get the following stacktrace:

```
> Task :detektCheck
Exception in thread "main" java.lang.ExceptionInInitializerError
        at io.gitlab.arturbosch.detekt.core.KtCompiler.<init>(KtCompiler.kt:17)
        at io.gitlab.arturbosch.detekt.core.KtTreeCompiler$Companion.instance(KtTreeCompiler.kt:16)
        at io.gitlab.arturbosch.detekt.core.DetektFacade.<init>(DetektFacade.kt:21)
        at io.gitlab.arturbosch.detekt.core.DetektFacade$Companion.create(DetektFacade.kt:83)
        at io.gitlab.arturbosch.detekt.core.DetektFacade$Companion.create(DetektFacade.kt:69)
        at io.gitlab.arturbosch.detekt.cli.Runner.execute(Runner.kt:20)
        at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:19)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 448
        at org.jetbrains.org.objectweb.asm.ClassReader.readUnsignedShort(ClassReader.java:2464)
        at org.jetbrains.org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:2525)
        at org.jetbrains.org.objectweb.asm.ClassReader.readModule(ClassReader.java:761)
        at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:646)
        at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:507)
        at org.jetbrains.kotlin.resolve.jvm.modules.JavaModuleInfo$Companion.read(JavaModuleInfo.kt:67)
        at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder.findSystemModule(CliJavaModuleFinder.kt:44)
        at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder.access$findSystemModule(CliJavaModuleFinder.kt:25)
        at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder$systemModules$1.invoke(CliJavaModuleFinder.kt:37)
        at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder$systemModules$1.invoke(CliJavaModuleFinder.kt:25)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:149)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:109)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:133)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:254)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:241)
        at kotlin.sequences.SequencesKt___SequencesKt.none(_Sequences.kt:1239)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.addModularRoots(ClasspathRootsResolver.kt:227)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.computeRoots(ClasspathRootsResolver.kt:124)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:79)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:230)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:114)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:409)
        at io.gitlab.arturbosch.detekt.api.ProjectExtensionKt.createKotlinCoreEnvironment(ProjectExtension.kt:33)
        at io.gitlab.arturbosch.detekt.api.ProjectExtensionKt.<clinit>(ProjectExtension.kt:24)
        ... 7 more
```

**Comment by arturbosch** [comment]
Interesting, looks to me like a compatibility issue of kotlin with java10. Thanks for reporting, we will pay attention.

**Comment by juergenzimmermann** [comment]
@arturbosch My Spring Boot application and all the tests are running fine with latest Kotlin and Java 10. It's just detekt which doesn't work anymore.

**Comment by arturbosch** [comment]
well with kotlin I mean the kotlin-compiler which had some api changes for java10 we are not aware of :)

**Comment by arturbosch** [comment]
I will take a look at this when SDK man has published a jdk10 build.

**Comment by Psynbiotik** [comment]
ping, java 10 is out now and should be in sdkman

**Comment by arturbosch** [comment]
Can't reproduce this with Java 10u23-openjdk, Kotlin 1.2.31 and detekt RC6-5.

**Comment by juergenzimmermann** [comment]
@arturbosch I cannot find RC6-5 at https://plugins.gradle.org. BTW, I'm having the issue with Windows 10.

**Comment by arturbosch** [comment]
Sorry, I mean RC6-5. If you can reproduce this with the same java and kotlin version, feel free to reopen this.
