### ISSUE TITLE
Gradle plugin - can't run detektCheck with JDK 9

### ISSUE THREAD

**Issue by samClarenc** [arturbosch/detekt#873]
Hello, 

I have a java 9 application that I want to "kotlinize". 

When I run 

`./gradlew detektCheck`

with a java 9, I get the following error : 
```

Exception in thread "main" java.lang.ExceptionInInitializerError
        at io.gitlab.arturbosch.detekt.core.KtCompiler.<init>(KtCompiler.kt:17)
        at io.gitlab.arturbosch.detekt.core.KtTreeCompiler$Companion.instance(KtTreeCompiler.kt:16)
        at io.gitlab.arturbosch.detekt.core.DetektFacade.<init>(DetektFacade.kt:21)
        at io.gitlab.arturbosch.detekt.core.DetektFacade$Companion.create(DetektFacade.kt:83)
        at io.gitlab.arturbosch.detekt.core.DetektFacade$Companion.create(DetektFacade.kt:69)
        at io.gitlab.arturbosch.detekt.cli.Runner.execute(Runner.kt:20)
        at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:19)
Caused by: java.lang.IllegalStateException: LOGGING: Loading modules: [java.se, javafx.base, javafx.controls, javafx.fxml, javafx.graphics, javafx.media, javafx.swing, javafx.web, jdk.accessibility, jdk.attach, jdk.compiler, jdk.dynalink, jdk.httpserver, jdk.incubator.httpclient, jdk.jartool, jdk.javadoc, jdk.jconsole, jdk.jdi, jdk.jfr, jdk.jshell, jdk.jsobject, jdk.management, jdk.management.cmm, jdk.management.jfr, jdk.management.resource, jdk.net, jdk.packager, jdk.packager.services, jdk.plugin.dom, jdk.scripting.nashorn, jdk.sctp, jdk.security.auth, jdk.security.jgss, jdk.unsupported, jdk.xml.dom, oracle.desktop, oracle.net, java.base, java.rmi, java.sql, java.logging, java.xml, java.scripting, java.management.rmi, java.management, java.xml.crypto, java.prefs, java.datatransfer, java.sql.rowset, java.naming, java.instrument, java.compiler, java.security.jgss, java.desktop, java.security.sasl, jdk.internal.jvmstat, jdk.management.agent, jdk.jdwp.agent, jdk.internal.ed, jdk.internal.opt, jdk.internal.le, jdk.jdeps, jdk.jlink] (no MessageCollector configured)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.report(ClasspathRootsResolver.kt:314)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.report$default(ClasspathRootsResolver.kt:312)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.addModularRoots(ClasspathRootsResolver.kt:254)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.computeRoots(ClasspathRootsResolver.kt:124)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:79)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:223)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:114)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:401)
        at io.gitlab.arturbosch.detekt.api.ProjectExtensionKt.<clinit>(ProjectExtension.kt:20)
        ... 7 more


FAILURE: Build failed with an exception.

```

This is my build.gradle : 
```

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "gradle.plugin.io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0.RC6-4"
    }
}

apply plugin: "io.gitlab.arturbosch.detekt"

detekt {
    version = "1.0.0.RC6"
    defaultProfile {
        config = file("detekt.yml")
        filters = ".*/resources/.*,.*/build/.*"
    }
}


```

And if I run the same detektCheck with a JDK 8, it passes successfully. 

Maybe I miss some --add-module parameter but I can't find any way to set it.

Any help will be appreciated !

**Comment by arturbosch** [comment]
This seems to be related with #566 and #747.
Do you use Windows?

**Comment by samClarenc** [comment]
Hello, thanx for your response, 

Yes it seems to be the same stacktrace than #566 . 

I use Ubuntu 16. 

I will try with detekt 1.0.0.RC6-1 version to test if it works !

**Comment by samClarenc** [comment]
It works with the version : 

```
detekt {
    version = "1.0.0.RC6-4"
}
```
I think my main problem now is more a sonar-scanner one : I don't know the version of detekt that is embedded in the sonar-scanner : I still get the error when I run it. 

It could be helpful if you have any idea about this. If I find something useful, I will update this ticket !

**Comment by samClarenc** [comment]
OK my misunderstanding was that the sonar-scanner does not "embed" sonar-kotlin but calls the sonarqube server. 

I updated  the sonar-kotlin plugin in my sonar and it now works. 

Thanks for your time, I close the ticket !

**Comment by arturbosch** [comment]
Awesome that it worked out for you!
